#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOP.BO
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FAJAS_BD")]
	public partial class FAJA_MODELDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertBuy_Bill(Buy_Bill instance);
    partial void UpdateBuy_Bill(Buy_Bill instance);
    partial void DeleteBuy_Bill(Buy_Bill instance);
    partial void InsertUsuarios(Usuarios instance);
    partial void UpdateUsuarios(Usuarios instance);
    partial void DeleteUsuarios(Usuarios instance);
    partial void InsertCompany(Company instance);
    partial void UpdateCompany(Company instance);
    partial void DeleteCompany(Company instance);
    partial void InsertDetail_Buy_Bill(Detail_Buy_Bill instance);
    partial void UpdateDetail_Buy_Bill(Detail_Buy_Bill instance);
    partial void DeleteDetail_Buy_Bill(Detail_Buy_Bill instance);
    partial void InsertDetail_Sale_Bill(Detail_Sale_Bill instance);
    partial void UpdateDetail_Sale_Bill(Detail_Sale_Bill instance);
    partial void DeleteDetail_Sale_Bill(Detail_Sale_Bill instance);
    partial void InsertProduct(Product instance);
    partial void UpdateProduct(Product instance);
    partial void DeleteProduct(Product instance);
    partial void InsertProduct_Color(Product_Color instance);
    partial void UpdateProduct_Color(Product_Color instance);
    partial void DeleteProduct_Color(Product_Color instance);
    partial void InsertProduct_Detail(Product_Detail instance);
    partial void UpdateProduct_Detail(Product_Detail instance);
    partial void DeleteProduct_Detail(Product_Detail instance);
    partial void InsertProduct_Size(Product_Size instance);
    partial void UpdateProduct_Size(Product_Size instance);
    partial void DeleteProduct_Size(Product_Size instance);
    partial void InsertProduct_Type(Product_Type instance);
    partial void UpdateProduct_Type(Product_Type instance);
    partial void DeleteProduct_Type(Product_Type instance);
    partial void InsertSale_Bill(Sale_Bill instance);
    partial void UpdateSale_Bill(Sale_Bill instance);
    partial void DeleteSale_Bill(Sale_Bill instance);
    #endregion
		
		//public FAJA_MODELDataContext() : 
		//		base(global::BOP.BO.Properties.Settings.Default.FAJAS_BDConnectionString, mappingSource)
		//{
		//	OnCreated();
		//}
		
		public FAJA_MODELDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FAJA_MODELDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FAJA_MODELDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FAJA_MODELDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Buy_Bill> Buy_Bill
		{
			get
			{
				return this.GetTable<Buy_Bill>();
			}
		}
		
		public System.Data.Linq.Table<Usuarios> Usuarios
		{
			get
			{
				return this.GetTable<Usuarios>();
			}
		}
		
		public System.Data.Linq.Table<Company> Company
		{
			get
			{
				return this.GetTable<Company>();
			}
		}
		
		public System.Data.Linq.Table<Detail_Buy_Bill> Detail_Buy_Bill
		{
			get
			{
				return this.GetTable<Detail_Buy_Bill>();
			}
		}
		
		public System.Data.Linq.Table<Detail_Sale_Bill> Detail_Sale_Bill
		{
			get
			{
				return this.GetTable<Detail_Sale_Bill>();
			}
		}
		
		public System.Data.Linq.Table<Product> Product
		{
			get
			{
				return this.GetTable<Product>();
			}
		}
		
		public System.Data.Linq.Table<Product_Color> Product_Color
		{
			get
			{
				return this.GetTable<Product_Color>();
			}
		}
		
		public System.Data.Linq.Table<Product_Detail> Product_Detail
		{
			get
			{
				return this.GetTable<Product_Detail>();
			}
		}
		
		public System.Data.Linq.Table<Product_Size> Product_Size
		{
			get
			{
				return this.GetTable<Product_Size>();
			}
		}
		
		public System.Data.Linq.Table<Product_Type> Product_Type
		{
			get
			{
				return this.GetTable<Product_Type>();
			}
		}
		
		public System.Data.Linq.Table<Sale_Bill> Sale_Bill
		{
			get
			{
				return this.GetTable<Sale_Bill>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.BOP_FAJAS_spListarUsuarios")]
		public ISingleResult<BOP_FAJAS_spListarUsuariosResult> BOP_FAJAS_spListarUsuarios()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<BOP_FAJAS_spListarUsuariosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.BOP_FAJAS_spListarDetalleProductos")]
		public ISingleResult<BOP_FAJAS_spListarDetalleProductosResult> BOP_FAJAS_spListarDetalleProductos([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PK_PRODUCTO", DbType="Int")] System.Nullable<int> pK_PRODUCTO)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pK_PRODUCTO);
			return ((ISingleResult<BOP_FAJAS_spListarDetalleProductosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.BOP_FAJAS_spListarProductos")]
		public ISingleResult<BOP_FAJAS_spListarProductosResult> BOP_FAJAS_spListarProductos()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<BOP_FAJAS_spListarProductosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.BOP_FAJAS_spListarProducto")]
		public ISingleResult<BOP_FAJAS_spListarProductoResult> BOP_FAJAS_spListarProducto([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PK_PRODUCTO", DbType="Int")] System.Nullable<int> pK_PRODUCTO)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pK_PRODUCTO);
			return ((ISingleResult<BOP_FAJAS_spListarProductoResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Buy_Bill")]
	public partial class Buy_Bill : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.DateTime _BuyBil_Date;
		
		private string _BuyBil_Description;
		
		private double _BuyBil_Total;
		
		private int _BuyBil_PK;
		
		private EntitySet<Detail_Buy_Bill> _Detail_Buy_Bill;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBuyBil_DateChanging(System.DateTime value);
    partial void OnBuyBil_DateChanged();
    partial void OnBuyBil_DescriptionChanging(string value);
    partial void OnBuyBil_DescriptionChanged();
    partial void OnBuyBil_TotalChanging(double value);
    partial void OnBuyBil_TotalChanged();
    partial void OnBuyBil_PKChanging(int value);
    partial void OnBuyBil_PKChanged();
    #endregion
		
		public Buy_Bill()
		{
			this._Detail_Buy_Bill = new EntitySet<Detail_Buy_Bill>(new Action<Detail_Buy_Bill>(this.attach_Detail_Buy_Bill), new Action<Detail_Buy_Bill>(this.detach_Detail_Buy_Bill));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BuyBil_Date", DbType="DateTime NOT NULL")]
		public System.DateTime BuyBil_Date
		{
			get
			{
				return this._BuyBil_Date;
			}
			set
			{
				if ((this._BuyBil_Date != value))
				{
					this.OnBuyBil_DateChanging(value);
					this.SendPropertyChanging();
					this._BuyBil_Date = value;
					this.SendPropertyChanged("BuyBil_Date");
					this.OnBuyBil_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BuyBil_Description", DbType="VarChar(50)")]
		public string BuyBil_Description
		{
			get
			{
				return this._BuyBil_Description;
			}
			set
			{
				if ((this._BuyBil_Description != value))
				{
					this.OnBuyBil_DescriptionChanging(value);
					this.SendPropertyChanging();
					this._BuyBil_Description = value;
					this.SendPropertyChanged("BuyBil_Description");
					this.OnBuyBil_DescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BuyBil_Total", DbType="Float NOT NULL")]
		public double BuyBil_Total
		{
			get
			{
				return this._BuyBil_Total;
			}
			set
			{
				if ((this._BuyBil_Total != value))
				{
					this.OnBuyBil_TotalChanging(value);
					this.SendPropertyChanging();
					this._BuyBil_Total = value;
					this.SendPropertyChanged("BuyBil_Total");
					this.OnBuyBil_TotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BuyBil_PK", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int BuyBil_PK
		{
			get
			{
				return this._BuyBil_PK;
			}
			set
			{
				if ((this._BuyBil_PK != value))
				{
					this.OnBuyBil_PKChanging(value);
					this.SendPropertyChanging();
					this._BuyBil_PK = value;
					this.SendPropertyChanged("BuyBil_PK");
					this.OnBuyBil_PKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Buy_Bill_Detail_Buy_Bill", Storage="_Detail_Buy_Bill", ThisKey="BuyBil_PK", OtherKey="DetBuyBil_FK_BuyBil")]
		public EntitySet<Detail_Buy_Bill> Detail_Buy_Bill
		{
			get
			{
				return this._Detail_Buy_Bill;
			}
			set
			{
				this._Detail_Buy_Bill.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Detail_Buy_Bill(Detail_Buy_Bill entity)
		{
			this.SendPropertyChanging();
			entity.Buy_Bill = this;
		}
		
		private void detach_Detail_Buy_Bill(Detail_Buy_Bill entity)
		{
			this.SendPropertyChanging();
			entity.Buy_Bill = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuarios")]
	public partial class Usuarios : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Use_Name;
		
		private string _Use_Password;
		
		private int _Use_PK;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUse_NameChanging(string value);
    partial void OnUse_NameChanged();
    partial void OnUse_PasswordChanging(string value);
    partial void OnUse_PasswordChanged();
    partial void OnUse_PKChanging(int value);
    partial void OnUse_PKChanged();
    #endregion
		
		public Usuarios()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Use_Name", DbType="NChar(20)")]
		public string Use_Name
		{
			get
			{
				return this._Use_Name;
			}
			set
			{
				if ((this._Use_Name != value))
				{
					this.OnUse_NameChanging(value);
					this.SendPropertyChanging();
					this._Use_Name = value;
					this.SendPropertyChanged("Use_Name");
					this.OnUse_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Use_Password", DbType="NChar(20)")]
		public string Use_Password
		{
			get
			{
				return this._Use_Password;
			}
			set
			{
				if ((this._Use_Password != value))
				{
					this.OnUse_PasswordChanging(value);
					this.SendPropertyChanging();
					this._Use_Password = value;
					this.SendPropertyChanged("Use_Password");
					this.OnUse_PasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Use_PK", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Use_PK
		{
			get
			{
				return this._Use_PK;
			}
			set
			{
				if ((this._Use_PK != value))
				{
					this.OnUse_PKChanging(value);
					this.SendPropertyChanging();
					this._Use_PK = value;
					this.SendPropertyChanged("Use_PK");
					this.OnUse_PKChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Company")]
	public partial class Company : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Com_Name;
		
		private string _Com_Id;
		
		private string _Com_Phone;
		
		private string _Com_Email;
		
		private string _Com_NickName;
		
		private int _Com_PK;
		
		private EntitySet<Sale_Bill> _Sale_Bill;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCom_NameChanging(string value);
    partial void OnCom_NameChanged();
    partial void OnCom_IdChanging(string value);
    partial void OnCom_IdChanged();
    partial void OnCom_PhoneChanging(string value);
    partial void OnCom_PhoneChanged();
    partial void OnCom_EmailChanging(string value);
    partial void OnCom_EmailChanged();
    partial void OnCom_NickNameChanging(string value);
    partial void OnCom_NickNameChanged();
    partial void OnCom_PKChanging(int value);
    partial void OnCom_PKChanged();
    #endregion
		
		public Company()
		{
			this._Sale_Bill = new EntitySet<Sale_Bill>(new Action<Sale_Bill>(this.attach_Sale_Bill), new Action<Sale_Bill>(this.detach_Sale_Bill));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Com_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Com_Name
		{
			get
			{
				return this._Com_Name;
			}
			set
			{
				if ((this._Com_Name != value))
				{
					this.OnCom_NameChanging(value);
					this.SendPropertyChanging();
					this._Com_Name = value;
					this.SendPropertyChanged("Com_Name");
					this.OnCom_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Com_Id", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Com_Id
		{
			get
			{
				return this._Com_Id;
			}
			set
			{
				if ((this._Com_Id != value))
				{
					this.OnCom_IdChanging(value);
					this.SendPropertyChanging();
					this._Com_Id = value;
					this.SendPropertyChanged("Com_Id");
					this.OnCom_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Com_Phone", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Com_Phone
		{
			get
			{
				return this._Com_Phone;
			}
			set
			{
				if ((this._Com_Phone != value))
				{
					this.OnCom_PhoneChanging(value);
					this.SendPropertyChanging();
					this._Com_Phone = value;
					this.SendPropertyChanged("Com_Phone");
					this.OnCom_PhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Com_Email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Com_Email
		{
			get
			{
				return this._Com_Email;
			}
			set
			{
				if ((this._Com_Email != value))
				{
					this.OnCom_EmailChanging(value);
					this.SendPropertyChanging();
					this._Com_Email = value;
					this.SendPropertyChanged("Com_Email");
					this.OnCom_EmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Com_NickName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Com_NickName
		{
			get
			{
				return this._Com_NickName;
			}
			set
			{
				if ((this._Com_NickName != value))
				{
					this.OnCom_NickNameChanging(value);
					this.SendPropertyChanging();
					this._Com_NickName = value;
					this.SendPropertyChanged("Com_NickName");
					this.OnCom_NickNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Com_PK", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Com_PK
		{
			get
			{
				return this._Com_PK;
			}
			set
			{
				if ((this._Com_PK != value))
				{
					this.OnCom_PKChanging(value);
					this.SendPropertyChanging();
					this._Com_PK = value;
					this.SendPropertyChanged("Com_PK");
					this.OnCom_PKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Company_Sale_Bill", Storage="_Sale_Bill", ThisKey="Com_PK", OtherKey="SalBil_FK_Com")]
		public EntitySet<Sale_Bill> Sale_Bill
		{
			get
			{
				return this._Sale_Bill;
			}
			set
			{
				this._Sale_Bill.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Sale_Bill(Sale_Bill entity)
		{
			this.SendPropertyChanging();
			entity.Company = this;
		}
		
		private void detach_Sale_Bill(Sale_Bill entity)
		{
			this.SendPropertyChanging();
			entity.Company = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Detail_Buy_Bill")]
	public partial class Detail_Buy_Bill : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private double _DetBuyBil_Quantity;
		
		private double _DetBuyBil_BuyPrice;
		
		private int _DetBuyBil_PK;
		
		private System.Nullable<int> _DetBuyBil_FK_BuyBil;
		
		private EntityRef<Buy_Bill> _Buy_Bill;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDetBuyBil_QuantityChanging(double value);
    partial void OnDetBuyBil_QuantityChanged();
    partial void OnDetBuyBil_BuyPriceChanging(double value);
    partial void OnDetBuyBil_BuyPriceChanged();
    partial void OnDetBuyBil_PKChanging(int value);
    partial void OnDetBuyBil_PKChanged();
    partial void OnDetBuyBil_FK_BuyBilChanging(System.Nullable<int> value);
    partial void OnDetBuyBil_FK_BuyBilChanged();
    #endregion
		
		public Detail_Buy_Bill()
		{
			this._Buy_Bill = default(EntityRef<Buy_Bill>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetBuyBil_Quantity", DbType="Float NOT NULL")]
		public double DetBuyBil_Quantity
		{
			get
			{
				return this._DetBuyBil_Quantity;
			}
			set
			{
				if ((this._DetBuyBil_Quantity != value))
				{
					this.OnDetBuyBil_QuantityChanging(value);
					this.SendPropertyChanging();
					this._DetBuyBil_Quantity = value;
					this.SendPropertyChanged("DetBuyBil_Quantity");
					this.OnDetBuyBil_QuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetBuyBil_BuyPrice", DbType="Float NOT NULL")]
		public double DetBuyBil_BuyPrice
		{
			get
			{
				return this._DetBuyBil_BuyPrice;
			}
			set
			{
				if ((this._DetBuyBil_BuyPrice != value))
				{
					this.OnDetBuyBil_BuyPriceChanging(value);
					this.SendPropertyChanging();
					this._DetBuyBil_BuyPrice = value;
					this.SendPropertyChanged("DetBuyBil_BuyPrice");
					this.OnDetBuyBil_BuyPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetBuyBil_PK", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int DetBuyBil_PK
		{
			get
			{
				return this._DetBuyBil_PK;
			}
			set
			{
				if ((this._DetBuyBil_PK != value))
				{
					this.OnDetBuyBil_PKChanging(value);
					this.SendPropertyChanging();
					this._DetBuyBil_PK = value;
					this.SendPropertyChanged("DetBuyBil_PK");
					this.OnDetBuyBil_PKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetBuyBil_FK_BuyBil", DbType="Int")]
		public System.Nullable<int> DetBuyBil_FK_BuyBil
		{
			get
			{
				return this._DetBuyBil_FK_BuyBil;
			}
			set
			{
				if ((this._DetBuyBil_FK_BuyBil != value))
				{
					if (this._Buy_Bill.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDetBuyBil_FK_BuyBilChanging(value);
					this.SendPropertyChanging();
					this._DetBuyBil_FK_BuyBil = value;
					this.SendPropertyChanged("DetBuyBil_FK_BuyBil");
					this.OnDetBuyBil_FK_BuyBilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Buy_Bill_Detail_Buy_Bill", Storage="_Buy_Bill", ThisKey="DetBuyBil_FK_BuyBil", OtherKey="BuyBil_PK", IsForeignKey=true)]
		public Buy_Bill Buy_Bill
		{
			get
			{
				return this._Buy_Bill.Entity;
			}
			set
			{
				Buy_Bill previousValue = this._Buy_Bill.Entity;
				if (((previousValue != value) 
							|| (this._Buy_Bill.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Buy_Bill.Entity = null;
						previousValue.Detail_Buy_Bill.Remove(this);
					}
					this._Buy_Bill.Entity = value;
					if ((value != null))
					{
						value.Detail_Buy_Bill.Add(this);
						this._DetBuyBil_FK_BuyBil = value.BuyBil_PK;
					}
					else
					{
						this._DetBuyBil_FK_BuyBil = default(Nullable<int>);
					}
					this.SendPropertyChanged("Buy_Bill");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Detail_Sale_Bill")]
	public partial class Detail_Sale_Bill : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private double _DetSalBil_Quantity;
		
		private System.Nullable<double> _DetSalBil_Detail;
		
		private int _DetBil_PK;
		
		private int _DetBil_FK_BuyBil;
		
		private int _DetBil_FK_ProDet;
		
		private EntityRef<Product_Detail> _Product_Detail;
		
		private EntityRef<Sale_Bill> _Sale_Bill;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDetSalBil_QuantityChanging(double value);
    partial void OnDetSalBil_QuantityChanged();
    partial void OnDetSalBil_DetailChanging(System.Nullable<double> value);
    partial void OnDetSalBil_DetailChanged();
    partial void OnDetBil_PKChanging(int value);
    partial void OnDetBil_PKChanged();
    partial void OnDetBil_FK_BuyBilChanging(int value);
    partial void OnDetBil_FK_BuyBilChanged();
    partial void OnDetBil_FK_ProDetChanging(int value);
    partial void OnDetBil_FK_ProDetChanged();
    #endregion
		
		public Detail_Sale_Bill()
		{
			this._Product_Detail = default(EntityRef<Product_Detail>);
			this._Sale_Bill = default(EntityRef<Sale_Bill>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetSalBil_Quantity", DbType="Float NOT NULL")]
		public double DetSalBil_Quantity
		{
			get
			{
				return this._DetSalBil_Quantity;
			}
			set
			{
				if ((this._DetSalBil_Quantity != value))
				{
					this.OnDetSalBil_QuantityChanging(value);
					this.SendPropertyChanging();
					this._DetSalBil_Quantity = value;
					this.SendPropertyChanged("DetSalBil_Quantity");
					this.OnDetSalBil_QuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetSalBil_Detail", DbType="Float")]
		public System.Nullable<double> DetSalBil_Detail
		{
			get
			{
				return this._DetSalBil_Detail;
			}
			set
			{
				if ((this._DetSalBil_Detail != value))
				{
					this.OnDetSalBil_DetailChanging(value);
					this.SendPropertyChanging();
					this._DetSalBil_Detail = value;
					this.SendPropertyChanged("DetSalBil_Detail");
					this.OnDetSalBil_DetailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetBil_PK", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int DetBil_PK
		{
			get
			{
				return this._DetBil_PK;
			}
			set
			{
				if ((this._DetBil_PK != value))
				{
					this.OnDetBil_PKChanging(value);
					this.SendPropertyChanging();
					this._DetBil_PK = value;
					this.SendPropertyChanged("DetBil_PK");
					this.OnDetBil_PKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetBil_FK_BuyBil", DbType="Int NOT NULL")]
		public int DetBil_FK_BuyBil
		{
			get
			{
				return this._DetBil_FK_BuyBil;
			}
			set
			{
				if ((this._DetBil_FK_BuyBil != value))
				{
					if (this._Sale_Bill.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDetBil_FK_BuyBilChanging(value);
					this.SendPropertyChanging();
					this._DetBil_FK_BuyBil = value;
					this.SendPropertyChanged("DetBil_FK_BuyBil");
					this.OnDetBil_FK_BuyBilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetBil_FK_ProDet", DbType="Int NOT NULL")]
		public int DetBil_FK_ProDet
		{
			get
			{
				return this._DetBil_FK_ProDet;
			}
			set
			{
				if ((this._DetBil_FK_ProDet != value))
				{
					if (this._Product_Detail.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDetBil_FK_ProDetChanging(value);
					this.SendPropertyChanging();
					this._DetBil_FK_ProDet = value;
					this.SendPropertyChanged("DetBil_FK_ProDet");
					this.OnDetBil_FK_ProDetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Product_Detail_Detail_Sale_Bill", Storage="_Product_Detail", ThisKey="DetBil_FK_ProDet", OtherKey="ProDet_PK", IsForeignKey=true)]
		public Product_Detail Product_Detail
		{
			get
			{
				return this._Product_Detail.Entity;
			}
			set
			{
				Product_Detail previousValue = this._Product_Detail.Entity;
				if (((previousValue != value) 
							|| (this._Product_Detail.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Product_Detail.Entity = null;
						previousValue.Detail_Sale_Bill.Remove(this);
					}
					this._Product_Detail.Entity = value;
					if ((value != null))
					{
						value.Detail_Sale_Bill.Add(this);
						this._DetBil_FK_ProDet = value.ProDet_PK;
					}
					else
					{
						this._DetBil_FK_ProDet = default(int);
					}
					this.SendPropertyChanged("Product_Detail");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sale_Bill_Detail_Sale_Bill", Storage="_Sale_Bill", ThisKey="DetBil_FK_BuyBil", OtherKey="SalBil_Pk", IsForeignKey=true)]
		public Sale_Bill Sale_Bill
		{
			get
			{
				return this._Sale_Bill.Entity;
			}
			set
			{
				Sale_Bill previousValue = this._Sale_Bill.Entity;
				if (((previousValue != value) 
							|| (this._Sale_Bill.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Sale_Bill.Entity = null;
						previousValue.Detail_Sale_Bill.Remove(this);
					}
					this._Sale_Bill.Entity = value;
					if ((value != null))
					{
						value.Detail_Sale_Bill.Add(this);
						this._DetBil_FK_BuyBil = value.SalBil_Pk;
					}
					else
					{
						this._DetBil_FK_BuyBil = default(int);
					}
					this.SendPropertyChanged("Sale_Bill");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Product")]
	public partial class Product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Pro_Name;
		
		private string _Pro_Description;
		
		private string _Pro_Code;
		
		private string _Pro_Photo;
		
		private double _Pro_SalePrice;
		
		private int _Pro_Pk;
		
		private int _Pro_Fk_ProTyp;
		
		private EntitySet<Product_Detail> _Product_Detail;
		
		private EntityRef<Product_Type> _Product_Type;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPro_NameChanging(string value);
    partial void OnPro_NameChanged();
    partial void OnPro_DescriptionChanging(string value);
    partial void OnPro_DescriptionChanged();
    partial void OnPro_CodeChanging(string value);
    partial void OnPro_CodeChanged();
    partial void OnPro_PhotoChanging(string value);
    partial void OnPro_PhotoChanged();
    partial void OnPro_SalePriceChanging(double value);
    partial void OnPro_SalePriceChanged();
    partial void OnPro_PkChanging(int value);
    partial void OnPro_PkChanged();
    partial void OnPro_Fk_ProTypChanging(int value);
    partial void OnPro_Fk_ProTypChanged();
    #endregion
		
		public Product()
		{
			this._Product_Detail = new EntitySet<Product_Detail>(new Action<Product_Detail>(this.attach_Product_Detail), new Action<Product_Detail>(this.detach_Product_Detail));
			this._Product_Type = default(EntityRef<Product_Type>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pro_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Pro_Name
		{
			get
			{
				return this._Pro_Name;
			}
			set
			{
				if ((this._Pro_Name != value))
				{
					this.OnPro_NameChanging(value);
					this.SendPropertyChanging();
					this._Pro_Name = value;
					this.SendPropertyChanged("Pro_Name");
					this.OnPro_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pro_Description", DbType="VarChar(50)")]
		public string Pro_Description
		{
			get
			{
				return this._Pro_Description;
			}
			set
			{
				if ((this._Pro_Description != value))
				{
					this.OnPro_DescriptionChanging(value);
					this.SendPropertyChanging();
					this._Pro_Description = value;
					this.SendPropertyChanged("Pro_Description");
					this.OnPro_DescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pro_Code", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Pro_Code
		{
			get
			{
				return this._Pro_Code;
			}
			set
			{
				if ((this._Pro_Code != value))
				{
					this.OnPro_CodeChanging(value);
					this.SendPropertyChanging();
					this._Pro_Code = value;
					this.SendPropertyChanged("Pro_Code");
					this.OnPro_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pro_Photo", DbType="VarChar(50)")]
		public string Pro_Photo
		{
			get
			{
				return this._Pro_Photo;
			}
			set
			{
				if ((this._Pro_Photo != value))
				{
					this.OnPro_PhotoChanging(value);
					this.SendPropertyChanging();
					this._Pro_Photo = value;
					this.SendPropertyChanged("Pro_Photo");
					this.OnPro_PhotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pro_SalePrice", DbType="Float NOT NULL")]
		public double Pro_SalePrice
		{
			get
			{
				return this._Pro_SalePrice;
			}
			set
			{
				if ((this._Pro_SalePrice != value))
				{
					this.OnPro_SalePriceChanging(value);
					this.SendPropertyChanging();
					this._Pro_SalePrice = value;
					this.SendPropertyChanged("Pro_SalePrice");
					this.OnPro_SalePriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pro_Pk", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Pro_Pk
		{
			get
			{
				return this._Pro_Pk;
			}
			set
			{
				if ((this._Pro_Pk != value))
				{
					this.OnPro_PkChanging(value);
					this.SendPropertyChanging();
					this._Pro_Pk = value;
					this.SendPropertyChanged("Pro_Pk");
					this.OnPro_PkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pro_Fk_ProTyp", DbType="Int NOT NULL")]
		public int Pro_Fk_ProTyp
		{
			get
			{
				return this._Pro_Fk_ProTyp;
			}
			set
			{
				if ((this._Pro_Fk_ProTyp != value))
				{
					if (this._Product_Type.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPro_Fk_ProTypChanging(value);
					this.SendPropertyChanging();
					this._Pro_Fk_ProTyp = value;
					this.SendPropertyChanged("Pro_Fk_ProTyp");
					this.OnPro_Fk_ProTypChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Product_Product_Detail", Storage="_Product_Detail", ThisKey="Pro_Pk", OtherKey="ProDet_FKk_Pro")]
		public EntitySet<Product_Detail> Product_Detail
		{
			get
			{
				return this._Product_Detail;
			}
			set
			{
				this._Product_Detail.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Product_Type_Product", Storage="_Product_Type", ThisKey="Pro_Fk_ProTyp", OtherKey="ProTyp_Pk", IsForeignKey=true)]
		public Product_Type Product_Type
		{
			get
			{
				return this._Product_Type.Entity;
			}
			set
			{
				Product_Type previousValue = this._Product_Type.Entity;
				if (((previousValue != value) 
							|| (this._Product_Type.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Product_Type.Entity = null;
						previousValue.Product.Remove(this);
					}
					this._Product_Type.Entity = value;
					if ((value != null))
					{
						value.Product.Add(this);
						this._Pro_Fk_ProTyp = value.ProTyp_Pk;
					}
					else
					{
						this._Pro_Fk_ProTyp = default(int);
					}
					this.SendPropertyChanged("Product_Type");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Product_Detail(Product_Detail entity)
		{
			this.SendPropertyChanging();
			entity.Product = this;
		}
		
		private void detach_Product_Detail(Product_Detail entity)
		{
			this.SendPropertyChanging();
			entity.Product = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Product_Color")]
	public partial class Product_Color : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ProCol_Name;
		
		private int _ProCol_PK;
		
		private EntitySet<Product_Detail> _Product_Detail;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProCol_NameChanging(string value);
    partial void OnProCol_NameChanged();
    partial void OnProCol_PKChanging(int value);
    partial void OnProCol_PKChanged();
    #endregion
		
		public Product_Color()
		{
			this._Product_Detail = new EntitySet<Product_Detail>(new Action<Product_Detail>(this.attach_Product_Detail), new Action<Product_Detail>(this.detach_Product_Detail));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProCol_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ProCol_Name
		{
			get
			{
				return this._ProCol_Name;
			}
			set
			{
				if ((this._ProCol_Name != value))
				{
					this.OnProCol_NameChanging(value);
					this.SendPropertyChanging();
					this._ProCol_Name = value;
					this.SendPropertyChanged("ProCol_Name");
					this.OnProCol_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProCol_PK", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ProCol_PK
		{
			get
			{
				return this._ProCol_PK;
			}
			set
			{
				if ((this._ProCol_PK != value))
				{
					this.OnProCol_PKChanging(value);
					this.SendPropertyChanging();
					this._ProCol_PK = value;
					this.SendPropertyChanged("ProCol_PK");
					this.OnProCol_PKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Product_Color_Product_Detail", Storage="_Product_Detail", ThisKey="ProCol_PK", OtherKey="ProDet_FKk_Pro")]
		public EntitySet<Product_Detail> Product_Detail
		{
			get
			{
				return this._Product_Detail;
			}
			set
			{
				this._Product_Detail.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Product_Detail(Product_Detail entity)
		{
			this.SendPropertyChanging();
			entity.Product_Color = this;
		}
		
		private void detach_Product_Detail(Product_Detail entity)
		{
			this.SendPropertyChanging();
			entity.Product_Color = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Product_Detail")]
	public partial class Product_Detail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ProDet_FK_ProCol;
		
		private int _ProDet_FK_ProSiz;
		
		private int _ProDet_FKk_Pro;
		
		private int _ProDet_PK;
		
		private EntitySet<Detail_Sale_Bill> _Detail_Sale_Bill;
		
		private EntityRef<Product> _Product;
		
		private EntityRef<Product_Color> _Product_Color;
		
		private EntityRef<Product_Size> _Product_Size;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProDet_FK_ProColChanging(int value);
    partial void OnProDet_FK_ProColChanged();
    partial void OnProDet_FK_ProSizChanging(int value);
    partial void OnProDet_FK_ProSizChanged();
    partial void OnProDet_FKk_ProChanging(int value);
    partial void OnProDet_FKk_ProChanged();
    partial void OnProDet_PKChanging(int value);
    partial void OnProDet_PKChanged();
    #endregion
		
		public Product_Detail()
		{
			this._Detail_Sale_Bill = new EntitySet<Detail_Sale_Bill>(new Action<Detail_Sale_Bill>(this.attach_Detail_Sale_Bill), new Action<Detail_Sale_Bill>(this.detach_Detail_Sale_Bill));
			this._Product = default(EntityRef<Product>);
			this._Product_Color = default(EntityRef<Product_Color>);
			this._Product_Size = default(EntityRef<Product_Size>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProDet_FK_ProCol", DbType="Int NOT NULL")]
		public int ProDet_FK_ProCol
		{
			get
			{
				return this._ProDet_FK_ProCol;
			}
			set
			{
				if ((this._ProDet_FK_ProCol != value))
				{
					this.OnProDet_FK_ProColChanging(value);
					this.SendPropertyChanging();
					this._ProDet_FK_ProCol = value;
					this.SendPropertyChanged("ProDet_FK_ProCol");
					this.OnProDet_FK_ProColChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProDet_FK_ProSiz", DbType="Int NOT NULL")]
		public int ProDet_FK_ProSiz
		{
			get
			{
				return this._ProDet_FK_ProSiz;
			}
			set
			{
				if ((this._ProDet_FK_ProSiz != value))
				{
					this.OnProDet_FK_ProSizChanging(value);
					this.SendPropertyChanging();
					this._ProDet_FK_ProSiz = value;
					this.SendPropertyChanged("ProDet_FK_ProSiz");
					this.OnProDet_FK_ProSizChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProDet_FKk_Pro", DbType="Int NOT NULL")]
		public int ProDet_FKk_Pro
		{
			get
			{
				return this._ProDet_FKk_Pro;
			}
			set
			{
				if ((this._ProDet_FKk_Pro != value))
				{
					if (((this._Product.HasLoadedOrAssignedValue || this._Product_Color.HasLoadedOrAssignedValue) 
								|| this._Product_Size.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProDet_FKk_ProChanging(value);
					this.SendPropertyChanging();
					this._ProDet_FKk_Pro = value;
					this.SendPropertyChanged("ProDet_FKk_Pro");
					this.OnProDet_FKk_ProChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProDet_PK", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ProDet_PK
		{
			get
			{
				return this._ProDet_PK;
			}
			set
			{
				if ((this._ProDet_PK != value))
				{
					this.OnProDet_PKChanging(value);
					this.SendPropertyChanging();
					this._ProDet_PK = value;
					this.SendPropertyChanged("ProDet_PK");
					this.OnProDet_PKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Product_Detail_Detail_Sale_Bill", Storage="_Detail_Sale_Bill", ThisKey="ProDet_PK", OtherKey="DetBil_FK_ProDet")]
		public EntitySet<Detail_Sale_Bill> Detail_Sale_Bill
		{
			get
			{
				return this._Detail_Sale_Bill;
			}
			set
			{
				this._Detail_Sale_Bill.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Product_Product_Detail", Storage="_Product", ThisKey="ProDet_FKk_Pro", OtherKey="Pro_Pk", IsForeignKey=true)]
		public Product Product
		{
			get
			{
				return this._Product.Entity;
			}
			set
			{
				Product previousValue = this._Product.Entity;
				if (((previousValue != value) 
							|| (this._Product.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Product.Entity = null;
						previousValue.Product_Detail.Remove(this);
					}
					this._Product.Entity = value;
					if ((value != null))
					{
						value.Product_Detail.Add(this);
						this._ProDet_FKk_Pro = value.Pro_Pk;
					}
					else
					{
						this._ProDet_FKk_Pro = default(int);
					}
					this.SendPropertyChanged("Product");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Product_Color_Product_Detail", Storage="_Product_Color", ThisKey="ProDet_FKk_Pro", OtherKey="ProCol_PK", IsForeignKey=true)]
		public Product_Color Product_Color
		{
			get
			{
				return this._Product_Color.Entity;
			}
			set
			{
				Product_Color previousValue = this._Product_Color.Entity;
				if (((previousValue != value) 
							|| (this._Product_Color.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Product_Color.Entity = null;
						previousValue.Product_Detail.Remove(this);
					}
					this._Product_Color.Entity = value;
					if ((value != null))
					{
						value.Product_Detail.Add(this);
						this._ProDet_FKk_Pro = value.ProCol_PK;
					}
					else
					{
						this._ProDet_FKk_Pro = default(int);
					}
					this.SendPropertyChanged("Product_Color");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Product_Size_Product_Detail", Storage="_Product_Size", ThisKey="ProDet_FKk_Pro", OtherKey="Siz_Pk", IsForeignKey=true)]
		public Product_Size Product_Size
		{
			get
			{
				return this._Product_Size.Entity;
			}
			set
			{
				Product_Size previousValue = this._Product_Size.Entity;
				if (((previousValue != value) 
							|| (this._Product_Size.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Product_Size.Entity = null;
						previousValue.Product_Detail.Remove(this);
					}
					this._Product_Size.Entity = value;
					if ((value != null))
					{
						value.Product_Detail.Add(this);
						this._ProDet_FKk_Pro = value.Siz_Pk;
					}
					else
					{
						this._ProDet_FKk_Pro = default(int);
					}
					this.SendPropertyChanged("Product_Size");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Detail_Sale_Bill(Detail_Sale_Bill entity)
		{
			this.SendPropertyChanging();
			entity.Product_Detail = this;
		}
		
		private void detach_Detail_Sale_Bill(Detail_Sale_Bill entity)
		{
			this.SendPropertyChanging();
			entity.Product_Detail = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Product_Size")]
	public partial class Product_Size : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Siz_Name;
		
		private int _Siz_Pk;
		
		private EntitySet<Product_Detail> _Product_Detail;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSiz_NameChanging(string value);
    partial void OnSiz_NameChanged();
    partial void OnSiz_PkChanging(int value);
    partial void OnSiz_PkChanged();
    #endregion
		
		public Product_Size()
		{
			this._Product_Detail = new EntitySet<Product_Detail>(new Action<Product_Detail>(this.attach_Product_Detail), new Action<Product_Detail>(this.detach_Product_Detail));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Siz_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Siz_Name
		{
			get
			{
				return this._Siz_Name;
			}
			set
			{
				if ((this._Siz_Name != value))
				{
					this.OnSiz_NameChanging(value);
					this.SendPropertyChanging();
					this._Siz_Name = value;
					this.SendPropertyChanged("Siz_Name");
					this.OnSiz_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Siz_Pk", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Siz_Pk
		{
			get
			{
				return this._Siz_Pk;
			}
			set
			{
				if ((this._Siz_Pk != value))
				{
					this.OnSiz_PkChanging(value);
					this.SendPropertyChanging();
					this._Siz_Pk = value;
					this.SendPropertyChanged("Siz_Pk");
					this.OnSiz_PkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Product_Size_Product_Detail", Storage="_Product_Detail", ThisKey="Siz_Pk", OtherKey="ProDet_FKk_Pro")]
		public EntitySet<Product_Detail> Product_Detail
		{
			get
			{
				return this._Product_Detail;
			}
			set
			{
				this._Product_Detail.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Product_Detail(Product_Detail entity)
		{
			this.SendPropertyChanging();
			entity.Product_Size = this;
		}
		
		private void detach_Product_Detail(Product_Detail entity)
		{
			this.SendPropertyChanging();
			entity.Product_Size = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Product_Type")]
	public partial class Product_Type : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ProTyp_Name;
		
		private int _ProTyp_Pk;
		
		private EntitySet<Product> _Product;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProTyp_NameChanging(string value);
    partial void OnProTyp_NameChanged();
    partial void OnProTyp_PkChanging(int value);
    partial void OnProTyp_PkChanged();
    #endregion
		
		public Product_Type()
		{
			this._Product = new EntitySet<Product>(new Action<Product>(this.attach_Product), new Action<Product>(this.detach_Product));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProTyp_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ProTyp_Name
		{
			get
			{
				return this._ProTyp_Name;
			}
			set
			{
				if ((this._ProTyp_Name != value))
				{
					this.OnProTyp_NameChanging(value);
					this.SendPropertyChanging();
					this._ProTyp_Name = value;
					this.SendPropertyChanged("ProTyp_Name");
					this.OnProTyp_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProTyp_Pk", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ProTyp_Pk
		{
			get
			{
				return this._ProTyp_Pk;
			}
			set
			{
				if ((this._ProTyp_Pk != value))
				{
					this.OnProTyp_PkChanging(value);
					this.SendPropertyChanging();
					this._ProTyp_Pk = value;
					this.SendPropertyChanged("ProTyp_Pk");
					this.OnProTyp_PkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Product_Type_Product", Storage="_Product", ThisKey="ProTyp_Pk", OtherKey="Pro_Fk_ProTyp")]
		public EntitySet<Product> Product
		{
			get
			{
				return this._Product;
			}
			set
			{
				this._Product.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Product(Product entity)
		{
			this.SendPropertyChanging();
			entity.Product_Type = this;
		}
		
		private void detach_Product(Product entity)
		{
			this.SendPropertyChanging();
			entity.Product_Type = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sale_Bill")]
	public partial class Sale_Bill : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _SalBil_ClientName;
		
		private string _SalBil_IdClient;
		
		private string _SalBil_PhoneClient;
		
		private string _SalBil_Description;
		
		private double _SalBil_GrossTotal;
		
		private double _SalBil_Tax;
		
		private double _SalBil_NetTotal;
		
		private string _SalBil_ClientEmail;
		
		private System.Nullable<double> _SalBil_Discount;
		
		private System.DateTime _SalBil_Date;
		
		private int _SalBil_Pk;
		
		private int _SalBil_FK_Com;
		
		private EntitySet<Detail_Sale_Bill> _Detail_Sale_Bill;
		
		private EntityRef<Company> _Company;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSalBil_ClientNameChanging(string value);
    partial void OnSalBil_ClientNameChanged();
    partial void OnSalBil_IdClientChanging(string value);
    partial void OnSalBil_IdClientChanged();
    partial void OnSalBil_PhoneClientChanging(string value);
    partial void OnSalBil_PhoneClientChanged();
    partial void OnSalBil_DescriptionChanging(string value);
    partial void OnSalBil_DescriptionChanged();
    partial void OnSalBil_GrossTotalChanging(double value);
    partial void OnSalBil_GrossTotalChanged();
    partial void OnSalBil_TaxChanging(double value);
    partial void OnSalBil_TaxChanged();
    partial void OnSalBil_NetTotalChanging(double value);
    partial void OnSalBil_NetTotalChanged();
    partial void OnSalBil_ClientEmailChanging(string value);
    partial void OnSalBil_ClientEmailChanged();
    partial void OnSalBil_DiscountChanging(System.Nullable<double> value);
    partial void OnSalBil_DiscountChanged();
    partial void OnSalBil_DateChanging(System.DateTime value);
    partial void OnSalBil_DateChanged();
    partial void OnSalBil_PkChanging(int value);
    partial void OnSalBil_PkChanged();
    partial void OnSalBil_FK_ComChanging(int value);
    partial void OnSalBil_FK_ComChanged();
    #endregion
		
		public Sale_Bill()
		{
			this._Detail_Sale_Bill = new EntitySet<Detail_Sale_Bill>(new Action<Detail_Sale_Bill>(this.attach_Detail_Sale_Bill), new Action<Detail_Sale_Bill>(this.detach_Detail_Sale_Bill));
			this._Company = default(EntityRef<Company>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalBil_ClientName", DbType="VarChar(50)")]
		public string SalBil_ClientName
		{
			get
			{
				return this._SalBil_ClientName;
			}
			set
			{
				if ((this._SalBil_ClientName != value))
				{
					this.OnSalBil_ClientNameChanging(value);
					this.SendPropertyChanging();
					this._SalBil_ClientName = value;
					this.SendPropertyChanged("SalBil_ClientName");
					this.OnSalBil_ClientNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalBil_IdClient", DbType="VarChar(50)")]
		public string SalBil_IdClient
		{
			get
			{
				return this._SalBil_IdClient;
			}
			set
			{
				if ((this._SalBil_IdClient != value))
				{
					this.OnSalBil_IdClientChanging(value);
					this.SendPropertyChanging();
					this._SalBil_IdClient = value;
					this.SendPropertyChanged("SalBil_IdClient");
					this.OnSalBil_IdClientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalBil_PhoneClient", DbType="VarChar(50)")]
		public string SalBil_PhoneClient
		{
			get
			{
				return this._SalBil_PhoneClient;
			}
			set
			{
				if ((this._SalBil_PhoneClient != value))
				{
					this.OnSalBil_PhoneClientChanging(value);
					this.SendPropertyChanging();
					this._SalBil_PhoneClient = value;
					this.SendPropertyChanged("SalBil_PhoneClient");
					this.OnSalBil_PhoneClientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalBil_Description", DbType="VarChar(50)")]
		public string SalBil_Description
		{
			get
			{
				return this._SalBil_Description;
			}
			set
			{
				if ((this._SalBil_Description != value))
				{
					this.OnSalBil_DescriptionChanging(value);
					this.SendPropertyChanging();
					this._SalBil_Description = value;
					this.SendPropertyChanged("SalBil_Description");
					this.OnSalBil_DescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalBil_GrossTotal", DbType="Float NOT NULL")]
		public double SalBil_GrossTotal
		{
			get
			{
				return this._SalBil_GrossTotal;
			}
			set
			{
				if ((this._SalBil_GrossTotal != value))
				{
					this.OnSalBil_GrossTotalChanging(value);
					this.SendPropertyChanging();
					this._SalBil_GrossTotal = value;
					this.SendPropertyChanged("SalBil_GrossTotal");
					this.OnSalBil_GrossTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalBil_Tax", DbType="Float NOT NULL")]
		public double SalBil_Tax
		{
			get
			{
				return this._SalBil_Tax;
			}
			set
			{
				if ((this._SalBil_Tax != value))
				{
					this.OnSalBil_TaxChanging(value);
					this.SendPropertyChanging();
					this._SalBil_Tax = value;
					this.SendPropertyChanged("SalBil_Tax");
					this.OnSalBil_TaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalBil_NetTotal", DbType="Float NOT NULL")]
		public double SalBil_NetTotal
		{
			get
			{
				return this._SalBil_NetTotal;
			}
			set
			{
				if ((this._SalBil_NetTotal != value))
				{
					this.OnSalBil_NetTotalChanging(value);
					this.SendPropertyChanging();
					this._SalBil_NetTotal = value;
					this.SendPropertyChanged("SalBil_NetTotal");
					this.OnSalBil_NetTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalBil_ClientEmail", DbType="VarChar(50)")]
		public string SalBil_ClientEmail
		{
			get
			{
				return this._SalBil_ClientEmail;
			}
			set
			{
				if ((this._SalBil_ClientEmail != value))
				{
					this.OnSalBil_ClientEmailChanging(value);
					this.SendPropertyChanging();
					this._SalBil_ClientEmail = value;
					this.SendPropertyChanged("SalBil_ClientEmail");
					this.OnSalBil_ClientEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalBil_Discount", DbType="Float")]
		public System.Nullable<double> SalBil_Discount
		{
			get
			{
				return this._SalBil_Discount;
			}
			set
			{
				if ((this._SalBil_Discount != value))
				{
					this.OnSalBil_DiscountChanging(value);
					this.SendPropertyChanging();
					this._SalBil_Discount = value;
					this.SendPropertyChanged("SalBil_Discount");
					this.OnSalBil_DiscountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalBil_Date", DbType="DateTime NOT NULL")]
		public System.DateTime SalBil_Date
		{
			get
			{
				return this._SalBil_Date;
			}
			set
			{
				if ((this._SalBil_Date != value))
				{
					this.OnSalBil_DateChanging(value);
					this.SendPropertyChanging();
					this._SalBil_Date = value;
					this.SendPropertyChanged("SalBil_Date");
					this.OnSalBil_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalBil_Pk", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SalBil_Pk
		{
			get
			{
				return this._SalBil_Pk;
			}
			set
			{
				if ((this._SalBil_Pk != value))
				{
					this.OnSalBil_PkChanging(value);
					this.SendPropertyChanging();
					this._SalBil_Pk = value;
					this.SendPropertyChanged("SalBil_Pk");
					this.OnSalBil_PkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalBil_FK_Com", DbType="Int NOT NULL")]
		public int SalBil_FK_Com
		{
			get
			{
				return this._SalBil_FK_Com;
			}
			set
			{
				if ((this._SalBil_FK_Com != value))
				{
					if (this._Company.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSalBil_FK_ComChanging(value);
					this.SendPropertyChanging();
					this._SalBil_FK_Com = value;
					this.SendPropertyChanged("SalBil_FK_Com");
					this.OnSalBil_FK_ComChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sale_Bill_Detail_Sale_Bill", Storage="_Detail_Sale_Bill", ThisKey="SalBil_Pk", OtherKey="DetBil_FK_BuyBil")]
		public EntitySet<Detail_Sale_Bill> Detail_Sale_Bill
		{
			get
			{
				return this._Detail_Sale_Bill;
			}
			set
			{
				this._Detail_Sale_Bill.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Company_Sale_Bill", Storage="_Company", ThisKey="SalBil_FK_Com", OtherKey="Com_PK", IsForeignKey=true)]
		public Company Company
		{
			get
			{
				return this._Company.Entity;
			}
			set
			{
				Company previousValue = this._Company.Entity;
				if (((previousValue != value) 
							|| (this._Company.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Company.Entity = null;
						previousValue.Sale_Bill.Remove(this);
					}
					this._Company.Entity = value;
					if ((value != null))
					{
						value.Sale_Bill.Add(this);
						this._SalBil_FK_Com = value.Com_PK;
					}
					else
					{
						this._SalBil_FK_Com = default(int);
					}
					this.SendPropertyChanged("Company");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Detail_Sale_Bill(Detail_Sale_Bill entity)
		{
			this.SendPropertyChanging();
			entity.Sale_Bill = this;
		}
		
		private void detach_Detail_Sale_Bill(Detail_Sale_Bill entity)
		{
			this.SendPropertyChanging();
			entity.Sale_Bill = null;
		}
	}
	
	public partial class BOP_FAJAS_spListarUsuariosResult
	{
		
		private int _Use_PK;
		
		private string _Use_Name;
		
		private string _Use_Password;
		
		public BOP_FAJAS_spListarUsuariosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Use_PK", DbType="Int NOT NULL")]
		public int Use_PK
		{
			get
			{
				return this._Use_PK;
			}
			set
			{
				if ((this._Use_PK != value))
				{
					this._Use_PK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Use_Name", DbType="NChar(20)")]
		public string Use_Name
		{
			get
			{
				return this._Use_Name;
			}
			set
			{
				if ((this._Use_Name != value))
				{
					this._Use_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Use_Password", DbType="NChar(20)")]
		public string Use_Password
		{
			get
			{
				return this._Use_Password;
			}
			set
			{
				if ((this._Use_Password != value))
				{
					this._Use_Password = value;
				}
			}
		}
	}
	
	public partial class BOP_FAJAS_spListarDetalleProductosResult
	{
		
		private int _ProDet_PK;
		
		private int _Pro_Pk;
		
		private int _Pro_Fk_ProTyp;
		
		private string _Pro_Code;
		
		private string _Pro_Description;
		
		private string _Pro_Name;
		
		private string _Pro_Photo;
		
		private double _Pro_SalePrice;
		
		private int _ProCol_PK;
		
		private string _ProCol_Name;
		
		private int _Siz_Pk;
		
		private string _Siz_Name;
		
		private int _ProTyp_Pk;
		
		private string _ProTyp_Name;
		
		public BOP_FAJAS_spListarDetalleProductosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProDet_PK", DbType="Int NOT NULL")]
		public int ProDet_PK
		{
			get
			{
				return this._ProDet_PK;
			}
			set
			{
				if ((this._ProDet_PK != value))
				{
					this._ProDet_PK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pro_Pk", DbType="Int NOT NULL")]
		public int Pro_Pk
		{
			get
			{
				return this._Pro_Pk;
			}
			set
			{
				if ((this._Pro_Pk != value))
				{
					this._Pro_Pk = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pro_Fk_ProTyp", DbType="Int NOT NULL")]
		public int Pro_Fk_ProTyp
		{
			get
			{
				return this._Pro_Fk_ProTyp;
			}
			set
			{
				if ((this._Pro_Fk_ProTyp != value))
				{
					this._Pro_Fk_ProTyp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pro_Code", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Pro_Code
		{
			get
			{
				return this._Pro_Code;
			}
			set
			{
				if ((this._Pro_Code != value))
				{
					this._Pro_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pro_Description", DbType="NVarChar(50)")]
		public string Pro_Description
		{
			get
			{
				return this._Pro_Description;
			}
			set
			{
				if ((this._Pro_Description != value))
				{
					this._Pro_Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pro_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Pro_Name
		{
			get
			{
				return this._Pro_Name;
			}
			set
			{
				if ((this._Pro_Name != value))
				{
					this._Pro_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pro_Photo", DbType="NVarChar(50)")]
		public string Pro_Photo
		{
			get
			{
				return this._Pro_Photo;
			}
			set
			{
				if ((this._Pro_Photo != value))
				{
					this._Pro_Photo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pro_SalePrice", DbType="Float NOT NULL")]
		public double Pro_SalePrice
		{
			get
			{
				return this._Pro_SalePrice;
			}
			set
			{
				if ((this._Pro_SalePrice != value))
				{
					this._Pro_SalePrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProCol_PK", DbType="Int NOT NULL")]
		public int ProCol_PK
		{
			get
			{
				return this._ProCol_PK;
			}
			set
			{
				if ((this._ProCol_PK != value))
				{
					this._ProCol_PK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProCol_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ProCol_Name
		{
			get
			{
				return this._ProCol_Name;
			}
			set
			{
				if ((this._ProCol_Name != value))
				{
					this._ProCol_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Siz_Pk", DbType="Int NOT NULL")]
		public int Siz_Pk
		{
			get
			{
				return this._Siz_Pk;
			}
			set
			{
				if ((this._Siz_Pk != value))
				{
					this._Siz_Pk = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Siz_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Siz_Name
		{
			get
			{
				return this._Siz_Name;
			}
			set
			{
				if ((this._Siz_Name != value))
				{
					this._Siz_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProTyp_Pk", DbType="Int NOT NULL")]
		public int ProTyp_Pk
		{
			get
			{
				return this._ProTyp_Pk;
			}
			set
			{
				if ((this._ProTyp_Pk != value))
				{
					this._ProTyp_Pk = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProTyp_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ProTyp_Name
		{
			get
			{
				return this._ProTyp_Name;
			}
			set
			{
				if ((this._ProTyp_Name != value))
				{
					this._ProTyp_Name = value;
				}
			}
		}
	}
	
	public partial class BOP_FAJAS_spListarProductosResult
	{
		
		private int _Pro_Pk;
		
		private int _Pro_Fk_ProTyp;
		
		private string _Pro_Code;
		
		private string _Pro_Description;
		
		private string _Pro_Name;
		
		private string _Pro_Photo;
		
		private double _Pro_SalePrice;
		
		private string _ProTyp_Name;
		
		public BOP_FAJAS_spListarProductosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pro_Pk", DbType="Int NOT NULL")]
		public int Pro_Pk
		{
			get
			{
				return this._Pro_Pk;
			}
			set
			{
				if ((this._Pro_Pk != value))
				{
					this._Pro_Pk = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pro_Fk_ProTyp", DbType="Int NOT NULL")]
		public int Pro_Fk_ProTyp
		{
			get
			{
				return this._Pro_Fk_ProTyp;
			}
			set
			{
				if ((this._Pro_Fk_ProTyp != value))
				{
					this._Pro_Fk_ProTyp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pro_Code", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Pro_Code
		{
			get
			{
				return this._Pro_Code;
			}
			set
			{
				if ((this._Pro_Code != value))
				{
					this._Pro_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pro_Description", DbType="NVarChar(50)")]
		public string Pro_Description
		{
			get
			{
				return this._Pro_Description;
			}
			set
			{
				if ((this._Pro_Description != value))
				{
					this._Pro_Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pro_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Pro_Name
		{
			get
			{
				return this._Pro_Name;
			}
			set
			{
				if ((this._Pro_Name != value))
				{
					this._Pro_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pro_Photo", DbType="NVarChar(50)")]
		public string Pro_Photo
		{
			get
			{
				return this._Pro_Photo;
			}
			set
			{
				if ((this._Pro_Photo != value))
				{
					this._Pro_Photo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pro_SalePrice", DbType="Float NOT NULL")]
		public double Pro_SalePrice
		{
			get
			{
				return this._Pro_SalePrice;
			}
			set
			{
				if ((this._Pro_SalePrice != value))
				{
					this._Pro_SalePrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProTyp_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ProTyp_Name
		{
			get
			{
				return this._ProTyp_Name;
			}
			set
			{
				if ((this._ProTyp_Name != value))
				{
					this._ProTyp_Name = value;
				}
			}
		}
	}
	
	public partial class BOP_FAJAS_spListarProductoResult
	{
		
		private int _Pro_Pk;
		
		private int _Pro_Fk_ProTyp;
		
		private string _Pro_Code;
		
		private string _Pro_Description;
		
		private string _Pro_Name;
		
		private string _Pro_Photo;
		
		private double _Pro_SalePrice;
		
		private string _ProTyp_Name;
		
		public BOP_FAJAS_spListarProductoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pro_Pk", DbType="Int NOT NULL")]
		public int Pro_Pk
		{
			get
			{
				return this._Pro_Pk;
			}
			set
			{
				if ((this._Pro_Pk != value))
				{
					this._Pro_Pk = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pro_Fk_ProTyp", DbType="Int NOT NULL")]
		public int Pro_Fk_ProTyp
		{
			get
			{
				return this._Pro_Fk_ProTyp;
			}
			set
			{
				if ((this._Pro_Fk_ProTyp != value))
				{
					this._Pro_Fk_ProTyp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pro_Code", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Pro_Code
		{
			get
			{
				return this._Pro_Code;
			}
			set
			{
				if ((this._Pro_Code != value))
				{
					this._Pro_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pro_Description", DbType="NVarChar(50)")]
		public string Pro_Description
		{
			get
			{
				return this._Pro_Description;
			}
			set
			{
				if ((this._Pro_Description != value))
				{
					this._Pro_Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pro_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Pro_Name
		{
			get
			{
				return this._Pro_Name;
			}
			set
			{
				if ((this._Pro_Name != value))
				{
					this._Pro_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pro_Photo", DbType="NVarChar(50)")]
		public string Pro_Photo
		{
			get
			{
				return this._Pro_Photo;
			}
			set
			{
				if ((this._Pro_Photo != value))
				{
					this._Pro_Photo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pro_SalePrice", DbType="Float NOT NULL")]
		public double Pro_SalePrice
		{
			get
			{
				return this._Pro_SalePrice;
			}
			set
			{
				if ((this._Pro_SalePrice != value))
				{
					this._Pro_SalePrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProTyp_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ProTyp_Name
		{
			get
			{
				return this._ProTyp_Name;
			}
			set
			{
				if ((this._ProTyp_Name != value))
				{
					this._ProTyp_Name = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
