<?xml version="1.0" encoding="utf-8"?><Database Name="FAJAS_BD" Class="FAJA_MODELDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=JINTAN\SQLEXPRESS;Initial Catalog=FAJAS_BD;Persist Security Info=True;User ID=sa" SettingsObjectName="BOP.BO.Properties.Settings" SettingsPropertyName="FAJAS_BDConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Buy_Bill" Member="Buy_Bill">
    <Type Name="Buy_Bill">
      <Column Name="BuyBil_Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="BuyBil_Description" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="BuyBil_Total" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="BuyBil_PK" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BuyBil_Status" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Association Name="Buy_Bill_Detail_Buy_Bill" Member="Detail_Buy_Bill" ThisKey="BuyBil_PK" OtherKey="DetBuyBil_FK_BuyBil" Type="Detail_Buy_Bill" />
    </Type>
  </Table>
  <Table Name="dbo.Sale_Bill" Member="Sale_Bill">
    <Type Name="Sale_Bill">
      <Column Name="SalBil_ClientName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SalBil_IdClient" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SalBil_PhoneClient" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SalBil_Description" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SalBil_GrossTotal" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="SalBil_Tax" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="SalBil_NetTotal" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="SalBil_ClientEmail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SalBil_Discount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SalBil_Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SalBil_Pk" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SalBil_FK_Com" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SalBil_Status" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Association Name="Sale_Bill_Detail_Sale_Bill" Member="Detail_Sale_Bill" ThisKey="SalBil_Pk" OtherKey="DetBil_FK_BuyBil" Type="Detail_Sale_Bill" />
      <Association Name="Company_Sale_Bill" Member="Company" ThisKey="SalBil_FK_Com" OtherKey="Com_PK" Type="Company" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Company" Member="Company">
    <Type Name="Company">
      <Column Name="Com_Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Com_Id" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Com_Phone" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Com_Email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Com_NickName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Com_PK" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="Company_Sale_Bill" Member="Sale_Bill" ThisKey="Com_PK" OtherKey="SalBil_FK_Com" Type="Sale_Bill" />
    </Type>
  </Table>
  <Table Name="dbo.Detail_Buy_Bill" Member="Detail_Buy_Bill">
    <Type Name="Detail_Buy_Bill">
      <Column Name="DetBuyBil_Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DetBuyBil_BuyPrice" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="DetBuyBil_PK" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DetBuyBil_FK_BuyBil" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DetBuyBil_FK_DetPro" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DetBuyBil_Status" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Association Name="Buy_Bill_Detail_Buy_Bill" Member="Buy_Bill" ThisKey="DetBuyBil_FK_BuyBil" OtherKey="BuyBil_PK" Type="Buy_Bill" IsForeignKey="true" />
      <Association Name="Product_Detail_Detail_Buy_Bill" Member="Product_Detail" ThisKey="DetBuyBil_FK_DetPro" OtherKey="ProDet_PK" Type="Product_Detail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Detail_Sale_Bill" Member="Detail_Sale_Bill">
    <Type Name="Detail_Sale_Bill">
      <Column Name="DetSalBil_Quantity" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="DetSalBil_Detail" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DetBil_PK" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DetBil_FK_BuyBil" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DetBil_FK_ProDet" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Sale_Bill_Detail_Sale_Bill" Member="Sale_Bill" ThisKey="DetBil_FK_BuyBil" OtherKey="SalBil_Pk" Type="Sale_Bill" IsForeignKey="true" />
      <Association Name="Product_Detail_Detail_Sale_Bill" Member="Product_Detail" ThisKey="DetBil_FK_ProDet" OtherKey="ProDet_PK" Type="Product_Detail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Product" Member="Product">
    <Type Name="Product">
      <Column Name="Pro_Name" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Pro_Description" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Pro_Code" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pro_Photo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Pro_SalePrice" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Pro_Pk" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Pro_Fk_ProTyp" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Pro_Status" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Association Name="Product_Product_Detail" Member="Product_Detail" ThisKey="Pro_Pk" OtherKey="ProDet_FKk_Pro" Type="Product_Detail" />
      <Association Name="Product_Type_Product" Member="Product_Type" ThisKey="Pro_Fk_ProTyp" OtherKey="ProTyp_Pk" Type="Product_Type" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Product_Color" Member="Product_Color">
    <Type Name="Product_Color">
      <Column Name="ProCol_Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ProCol_PK" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="Product_Color_Product_Detail" Member="Product_Detail" ThisKey="ProCol_PK" OtherKey="ProDet_FK_ProCol" Type="Product_Detail" />
    </Type>
  </Table>
  <Table Name="dbo.Product_Detail" Member="Product_Detail">
    <Type Name="Product_Detail">
      <Column Name="ProDet_FK_ProCol" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProDet_FK_ProSiz" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProDet_FKk_Pro" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProDet_PK" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProDet_Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProDet_Status" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Association Name="Product_Detail_Detail_Buy_Bill" Member="Detail_Buy_Bill" ThisKey="ProDet_PK" OtherKey="DetBuyBil_FK_DetPro" Type="Detail_Buy_Bill" />
      <Association Name="Product_Detail_Detail_Sale_Bill" Member="Detail_Sale_Bill" ThisKey="ProDet_PK" OtherKey="DetBil_FK_ProDet" Type="Detail_Sale_Bill" />
      <Association Name="Product_Product_Detail" Member="Product" ThisKey="ProDet_FKk_Pro" OtherKey="Pro_Pk" Type="Product" IsForeignKey="true" />
      <Association Name="Product_Color_Product_Detail" Member="Product_Color" ThisKey="ProDet_FK_ProCol" OtherKey="ProCol_PK" Type="Product_Color" IsForeignKey="true" />
      <Association Name="Product_Size_Product_Detail" Member="Product_Size" ThisKey="ProDet_FKk_Pro" OtherKey="Siz_Pk" Type="Product_Size" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Product_Size" Member="Product_Size">
    <Type Name="Product_Size">
      <Column Name="Siz_Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Siz_Pk" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="Product_Size_Product_Detail" Member="Product_Detail" ThisKey="Siz_Pk" OtherKey="ProDet_FKk_Pro" Type="Product_Detail" />
    </Type>
  </Table>
  <Table Name="dbo.Product_Type" Member="Product_Type">
    <Type Name="Product_Type">
      <Column Name="ProTyp_Name" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ProTyp_Pk" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="Product_Type_Product" Member="Product" ThisKey="ProTyp_Pk" OtherKey="Pro_Fk_ProTyp" Type="Product" />
    </Type>
  </Table>
  <Table Name="dbo.Usuarios" Member="Usuarios">
    <Type Name="Usuarios">
      <Column Name="Use_Name" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Use_Password" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Use_PK" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.BOP_FAJAS_spBuscarProductos" Method="BOP_FAJAS_spBuscarProductos">
    <Parameter Name="color" Type="System.Int32" DbType="Int" />
    <Parameter Name="size" Type="System.Int32" DbType="Int" />
    <ElementType Name="BOP_FAJAS_spBuscarProductosResult">
      <Column Name="ProDet_PK" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProDet_Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Pro_Pk" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Pro_Fk_ProTyp" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Pro_Code" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pro_Description" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Pro_Name" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Pro_Photo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Pro_SalePrice" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ProCol_PK" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProCol_Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Siz_Pk" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Siz_Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ProTyp_Pk" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProTyp_Name" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.BOP_FAJAS_spReporteVentaRangoFechas" Method="BOP_FAJAS_spReporteVentaRangoFechas">
    <Parameter Name="Inicio" Parameter="inicio" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Final" Parameter="final" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="BOP_FAJAS_spReporteVentaRangoFechasResult">
      <Column Name="FechaInicio" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaFinal" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SalBil_ClientEmail" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SalBil_PhoneClient" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SalBil_IdClient" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SalBil_ClientName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SalBil_Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SalBil_Description" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SalBil_Discount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SalBil_GrossTotal" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="SalBil_NetTotal" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="SalBil_Tax" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="SalBil_Pk" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.BOP_FAJAS_spCuerpoVenta" Method="BOP_FAJAS_spCuerpoVenta">
    <Parameter Name="Venta" Parameter="venta" Type="System.Int32" DbType="Int" />
    <ElementType Name="BOP_FAJAS_spCuerpoVentaResult">
      <Column Name="DetSalBil_Detail" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DetSalBil_Quantity" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Pro_Code" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pro_Description" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Pro_SalePrice" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="neto" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="NVarChar(101) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.BOP_FAJAS_spEncabezadoVenta" Method="BOP_FAJAS_spEncabezadoVenta">
    <Parameter Name="Venta" Parameter="venta" Type="System.Int32" DbType="Int" />
    <ElementType Name="BOP_FAJAS_spEncabezadoVentaResult">
      <Column Name="Com_Email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Com_Id" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Com_Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Com_NickName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Com_Phone" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Com_PK" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SalBil_ClientEmail" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SalBil_PhoneClient" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SalBil_IdClient" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SalBil_ClientName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SalBil_Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SalBil_Description" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SalBil_Discount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SalBil_GrossTotal" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="SalBil_NetTotal" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="SalBil_Tax" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="SalBil_Pk" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.BOP_FAJAS_spListarDetalleCompras" Method="BOP_FAJAS_spListarDetalleCompras">
    <Parameter Name="PK_BILL" Parameter="pK_BILL" Type="System.Int32" DbType="Int" />
    <Parameter Name="Estado" Parameter="estado" Type="System.String" DbType="VarChar(1)" />
    <ElementType Name="BOP_FAJAS_spListarDetalleComprasResult">
      <Column Name="DetBuyBil_PK" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DetBuyBil_Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DetBuyBil_BuyPrice" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Pro_Pk" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Pro_Name" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Pro_Code" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Siz_Pk" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Siz_Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ProCol_PK" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProCol_Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.BOP_FAJAS_spListarDetalleProductos" Method="BOP_FAJAS_spListarDetalleProductos">
    <Parameter Name="PK_PRODUCTO" Parameter="pK_PRODUCTO" Type="System.Int32" DbType="Int" />
    <ElementType Name="BOP_FAJAS_spListarDetalleProductosResult">
      <Column Name="ProDet_PK" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProDet_Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Pro_Pk" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Pro_Fk_ProTyp" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Pro_Code" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pro_Description" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Pro_Name" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Pro_Photo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Pro_SalePrice" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ProCol_PK" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProCol_Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Siz_Pk" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Siz_Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ProTyp_Pk" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProTyp_Name" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.BOP_FAJAS_spListarDetalleVentas" Method="BOP_FAJAS_spListarDetalleVentas">
    <Parameter Name="PK_BILL" Parameter="pK_BILL" Type="System.Int32" DbType="Int" />
    <ElementType Name="BOP_FAJAS_spListarDetalleVentasResult">
      <Column Name="SalBil_Status" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="DetBil_PK" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DetSalBil_Detail" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DetSalBil_Quantity" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="DetBil_FK_ProDet" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Pro_Pk" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Pro_Name" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Pro_Code" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pro_SalePrice" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Siz_Pk" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Siz_Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ProCol_PK" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProCol_Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.BOP_FAJAS_spListarProducto" Method="BOP_FAJAS_spListarProducto">
    <Parameter Name="PK_PRODUCTO" Parameter="pK_PRODUCTO" Type="System.Int32" DbType="Int" />
    <ElementType Name="BOP_FAJAS_spListarProductoResult">
      <Column Name="Pro_Pk" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Pro_Fk_ProTyp" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Pro_Code" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pro_Description" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Pro_Name" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Pro_Photo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Pro_SalePrice" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ProTyp_Name" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.BOP_FAJAS_spListarProductos" Method="BOP_FAJAS_spListarProductos">
    <ElementType Name="BOP_FAJAS_spListarProductosResult">
      <Column Name="Pro_Pk" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Pro_Fk_ProTyp" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Pro_Code" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pro_Description" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Pro_Name" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Pro_Photo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Pro_SalePrice" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ProTyp_Name" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.BOP_FAJAS_spListarUsuarios" Method="BOP_FAJAS_spListarUsuarios">
    <ElementType Name="BOP_FAJAS_spListarUsuariosResult">
      <Column Name="Use_PK" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Use_Name" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Use_Password" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.BOP_FAJAS_spReporteCompraRangoFechas" Method="BOP_FAJAS_spReporteCompraRangoFechas">
    <Parameter Name="Inicio" Parameter="inicio" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Final" Parameter="final" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="BOP_FAJAS_spReporteCompraRangoFechasResult">
      <Column Name="FechaInicio" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaFinal" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BuyBil_Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="BuyBil_Total" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="BuyBil_Description" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="BuyBil_PK" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>